name: Run tests

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt update
        sudo apt install -y google-chrome-stable
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Download temp files
      run: cd ffmpeg_wasm_bridge && curl -o audio.ogg https://upload.wikimedia.org/wikipedia/commons/a/a0/Chopin_Nocturne_21_in_C_minor_Posthumous_Diana_Hughes.ogg && curl -o image0.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Comet_Tsuchinshan–ATLAS_over_Ohio_%28Composite%29.jpg/500px-Comet_Tsuchinshan–ATLAS_over_Ohio_%28Composite%29.jpg && curl -o image1.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/DDG-125_acceptance_trials.jpg/1080px-DDG-125_acceptance_trials.jpg
    - name: Run tests
      run: cd ffmpeg_wasm_bridge && python3 tests.py audio.ogg image0.jpg image1.jpg --autorun-chrome
    