name: Run tests

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - uses: browser-actions/setup-firefox@v1
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Download temp files
      run: cd ffmpeg_wasm_bridge && curl -o audio.ogg https://upload.wikimedia.org/wikipedia/commons/a/a0/Chopin_Nocturne_21_in_C_minor_Posthumous_Diana_Hughes.ogg && curl -o image0.jpg https://upload.wikimedia.org/wikipedia/commons/1/19/Gardens_by_the_Bay%2C_Marina_Bay%2C_Singapur%2C_2023-08-19%2C_DD_05-07_HDR.jpg && curl -o image1.jpg https://upload.wikimedia.org/wikipedia/commons/0/03/Itsukushima-jinja_torii%2C_Miyajima%2C_Japan%2C_20240816_1728_4082.jpg
    - name: Run tests
      run: cd ffmpeg_wasm_bridge && python3 tests.py audio.ogg image0.jpg image1.jpg
    